# desktop/vault_builder.py
import re
import os
import json
from jinja2 import Template

class MarkdownVaultBuilder:
    """
    Transforms database notes and academic records into an Obsidian-ready Markdown vault.
    Implements Expert Mode with YAML frontmatter and Wiki-link auto-remapping.
    """
    
    NOTE_TEMPLATE = """---
tags: [{{ tags | join(', ') }}]
date: {{ date }}
type: {{ type }}
source: Student Planner OS V3
---

# {{ title }}

{% if class_name %}
**Class:** [[{{ class_name }}]]
{% endif %}

## Content
{{ content }}

---
*Generated by Knowledge Lab Exporter*
"""

    def __init__(self, export_dir, classes=None):
        self.export_dir = export_dir
        self.classes = classes or []
        self.wiki_link_pattern = re.compile(r'\b(' + '|'.join(map(re.escape, self.classes)) + r')\b', re.IGNORECASE) if self.classes else None

    def _apply_wiki_links(self, text):
        if not self.wiki_link_pattern:
            return text
        # Convert "Biology" to [[Biology]]
        return self.wiki_link_pattern.sub(r'[[\1]]', text)

    def export_note(self, note_data):
        """
        note_data = {
            "title": "...",
            "content": "...",
            "tags": ["..."],
            "date": "...",
            "type": "...",
            "class_name": "..."
        }
        """
        # 1. Process formatting (Auto Wiki-links)
        formatted_content = self._apply_wiki_links(note_data.get("content", ""))
        
        # 2. Render Template
        template = Template(self.NOTE_TEMPLATE)
        markdown_content = template.render(
            title=note_data.get("title"),
            tags=note_data.get("tags", []),
            date=note_data.get("date"),
            type=note_data.get("type", "Note"),
            class_name=note_data.get("class_name"),
            content=formatted_content
        )
        
        # 3. Save File
        safe_title = re.sub(r'[\\/*?:"<>|]', "", note_data.get("title")).strip()
        file_path = os.path.join(self.export_dir, f"{safe_title}.md")
        
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(markdown_content)
        
        return file_path

    def batch_export(self, notes_list):
        if not os.path.exists(self.export_dir):
            os.makedirs(self.export_dir)
            
        results = []
        for note in notes_list:
            results.append(self.export_note(note))
        return results
